<?php

declare(strict_types=1);

/**
 * ═══════════════════════════════════════════════════════════════════════════
 *  EDGE — web-server front configuration
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * Edge generates this host's nginx / Apache configuration from your registered
 * project domains. This file is the single place that decides WHAT it generates.
 *
 * ── HOW TO USE THIS FILE ───────────────────────────────────────────────────
 *
 * You normally do NOT edit this file. Every value reads an environment variable
 * first, so the usual workflow is:
 *
 *   1. Set the variable in your project's `.env`         ← preferred
 *        EDGE_TLS_MODE=none
 *        EDGE_MAX_BODY=100m
 *
 *   2. Or override one value for a single run
 *        EDGE_HTTP_PRELUDE=1 hkm cli -p shop edge:apply --dry-run
 *
 *   3. Or copy this file to projects/<name>/config/edge.php and change it there.
 *      That copy is DEEP-MERGED over this one, so you only write the keys you
 *      actually want to change — everything else keeps the defaults below.
 *
 * ALWAYS preview before writing:
 *        hkm cli -p <project> edge:apply --dry-run
 * That prints the exact config the settings below produce. Nothing is written.
 *
 * ── READING AN ENTRY ───────────────────────────────────────────────────────
 *
 *   'key' => …            ENV_VAR              default: value
 *   What it does · when to change it · why it matters.
 *
 * Booleans accept 1/0, true/false, yes/no, on/off. Lists are comma-separated.
 * An empty value usually means "disabled" or "auto" — each entry says which.
 *
 * ── THE SIX GROUPS BELOW ───────────────────────────────────────────────────
 *
 *   1. Ports & TLS ................ which ports, which certificate, HTTPS mode
 *   2. Caching & compression ...... what browsers and CDNs may keep
 *   3. Security ................... headers, deny lists, limits, lockdown
 *   4. Strategy & output .......... which server, where the file is written
 *   5. Domains & hosts ............ where hostnames come from, /etc/hosts
 *   6. Serving & environment ...... PHP-FPM vs OpenSwoole, injected env
 *
 * Full guides: plugins/Edge/README.md (architecture) · USAGE.md (commands).
 */

/**
 * Where the GLOBAL project registry lives (projects.json + platform.json).
 *
 * Edge is a HOST-level tool: it must see every project and its domains, which
 * lives in the kernel home — NOT in the current project's base_path.
 *
 * Resolution order (first hit wins):
 *   1. EDGE_PROJECTS_DIR   explicit override — point Edge at any registry
 *   2. PSP_PROJECTS_DIR    exported by the launcher
 *   3. HKM_KERNEL_HOME/projects
 *   4. base_path('projects')
 *
 * Set EDGE_PROJECTS_DIR when testing against a copied registry, or when the
 * kernel home is not where the projects actually live.
 */
$__edgeProjectsDir = (static function (): string {
    $explicit = (string) env('EDGE_PROJECTS_DIR', '');
    if ($explicit !== '') {
        return rtrim($explicit, '/');
    }
    $psp = (string) env('PSP_PROJECTS_DIR', '');
    if ($psp !== '') {
        return rtrim($psp, '/');
    }
    $home = (string) env('HKM_KERNEL_HOME', '');
    if ($home !== '') {
        return rtrim($home, '/') . '/projects';
    }
    return base_path('projects');
})();

return [

    // ═══════════════════════════════════════════════════════════════════════
    //  1 · PORTS & TLS
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * 'listen'  EDGE_LISTEN_PORT  default: 443
     *
     * The public HTTPS port. Also the port the SNI stream splitter binds when
     * nginx fronts Apache.
     *
     * Change it when: another service already owns :443, or you are testing on
     * an unprivileged port (8443) without root.
     */
    'listen' => (int) (env('EDGE_LISTEN_PORT') ?: 443),

    /**
     * 'http'  EDGE_HTTP_PORT  default: 80
     *
     * The public plain-HTTP port. Used by tls mode `none` (the only listener)
     * and by mode `both` (the redirect-to-HTTPS listener).
     */
    'http' => (int) (env('EDGE_HTTP_PORT') ?: 80),

    /**
     * 'tls.mode'  EDGE_TLS_MODE  default: ssl        values: ssl | none | both
     *
     *   ssl   one `listen 443 ssl` server. HTTP/2, TLS pinning, HSTS.
     *         Needs a real certificate or `nginx -t` fails.
     *   none  one `listen 80` server, plain HTTP, no certificate, no HSTS.
     *         The right choice on a box that has no cert yet.
     *   both  a `listen 80` server that serves the ACME challenge and then
     *         301-redirects to HTTPS, PLUS the `listen 443 ssl` server.
     *
     * Per run: `edge:apply --tls=ssl|none|both` (or `--no-ssl` for none).
     * Note `--local` defaults to `none` so a dev box needs no self-signed cert.
     *
     * Benefit of `both`: certificates can still be issued and renewed over
     * plain :80 (the challenge passes through BEFORE the redirect) while every
     * real visitor is pushed to HTTPS.
     */
    'tls' => [
        'mode' => (string) (env('EDGE_TLS_MODE') ?: 'ssl'),
    ],

    /**
     * 'ssl.cert' / 'ssl.key'  EDGE_SSL_CERT / EDGE_SSL_KEY
     * default: /etc/ssl/certs/hkm-edge.pem · /etc/ssl/private/hkm-edge.key
     *
     * The certificate used by the nginx-only and Apache templates. For
     * Let's Encrypt point these at fullchain.pem / privkey.pem.
     *
     * Per run: `edge:apply --ssl-cert=/path --ssl-key=/path`.
     */
    'ssl' => [
        'cert' => (string) (env('EDGE_SSL_CERT') ?: '/etc/ssl/certs/hkm-edge.pem'),
        'key'  => (string) (env('EDGE_SSL_KEY')  ?: '/etc/ssl/private/hkm-edge.key'),
    ],

    /**
     * 'ssl_hardening'  —  what TLS actually negotiates.
     *
     *   protocols  EDGE_SSL_PROTOCOLS  default: TLSv1.2 TLSv1.3
     *     Pinned explicitly because relying on the nginx build default has
     *     historically left TLS 1.0/1.1 enabled. Emitted on both nginx and
     *     Apache (translated to Apache's `-all +TLSv1.2 …` form).
     *
     *   ciphers  EDGE_SSL_CIPHERS  default: '' (built-in modern suite)
     *     Empty keeps Edge's ECDHE/AES-GCM/CHACHA20 list. Override only if a
     *     compliance profile requires a specific suite.
     *
     *   stapling  EDGE_SSL_STAPLING  default: false
     *     OCSP stapling — the server fetches the revocation proof itself, so
     *     visitors do not have to call the CA (faster, more private).
     *     Keep OFF for Cloudflare Origin CA certificates: they are not publicly
     *     chained, so there is no responder to staple from.
     *
     *   resolver / resolver_timeout  EDGE_RESOLVER / EDGE_RESOLVER_TIMEOUT
     *     Only used when stapling is on. WITHOUT a resolver nginx cannot reach
     *     the CA's responder: it logs "no resolver defined to resolve …" and
     *     silently never staples, making the setting a no-op.
     */
    'ssl_hardening' => [
        'protocols' => (string) (env('EDGE_SSL_PROTOCOLS') ?: 'TLSv1.2 TLSv1.3'),
        'ciphers'   => (string) (env('EDGE_SSL_CIPHERS') ?: ''),
        'stapling'  => filter_var(env('EDGE_SSL_STAPLING', 'false'), FILTER_VALIDATE_BOOL),
        'resolver'         => (string) (env('EDGE_RESOLVER') ?: '127.0.0.53 1.1.1.1 8.8.8.8'),
        'resolver_timeout' => (string) (env('EDGE_RESOLVER_TIMEOUT') ?: '5s'),
    ],

    /**
     * 'hsts'  —  Strict-Transport-Security: "never speak plain HTTP to me again".
     *
     *   enabled             EDGE_HSTS              default: true
     *   max_age             EDGE_HSTS_MAX_AGE      default: 31536000 (1 year)
     *   dev_max_age         EDGE_HSTS_DEV_MAX_AGE  default: 300 (5 min)
     *   include_subdomains  EDGE_HSTS_SUBDOMAINS   default: true
     *   preload             EDGE_HSTS_PRELOAD      default: false
     *
     * Emitted ONLY for TLS modes — never on plain HTTP.
     *
     * The DEVELOPMENT profile always uses the short `dev_max_age`, with no
     * subdomains and no preload, so a dev machine is never pinned to HTTPS for
     * a year by a browser that then refuses to load it over :80.
     *
     * `preload` submits your domain to a list baked into browsers. It is very
     * hard to reverse (months), so it stays opt-in and is never a silent default.
     */
    'hsts' => [
        'enabled'            => filter_var(env('EDGE_HSTS', 'true'), FILTER_VALIDATE_BOOL),
        'max_age'            => (int) (env('EDGE_HSTS_MAX_AGE') ?: 31536000),
        'dev_max_age'        => (int) (env('EDGE_HSTS_DEV_MAX_AGE') ?: 300),
        'include_subdomains' => filter_var(env('EDGE_HSTS_SUBDOMAINS', 'true'), FILTER_VALIDATE_BOOL),
        'preload'            => filter_var(env('EDGE_HSTS_PRELOAD', 'false'), FILTER_VALIDATE_BOOL),
    ],

    // ═══════════════════════════════════════════════════════════════════════
    //  2 · CACHING & COMPRESSION
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * 'cache'  —  what the browser and any CDN are allowed to keep.
     *
     * The DEVELOPMENT vs PRODUCTION profile is derived from APP_ENV alone
     * (local/development → DEVELOPMENT, production → PRODUCTION, anything
     * unknown → DEVELOPMENT — see Domain\CacheProfile). It is deliberately not
     * configurable here, and never inferred from the kernel mode (HKM_DEV), so
     * "which kernel am I running" and "how are assets cached" stay independent.
     *
     *   DEVELOPMENT  HTML, index.php and every asset are no-store → a refresh
     *                always refetches. No more "why is my CSS stale?".
     *   PRODUCTION   HTML/index.php still never cached; fingerprinted assets
     *                cached long-term and immutable.
     *
     *   browser_assets      EDGE_CACHE_ASSETS       default: true
     *       Cache versioned static assets at all (production profile).
     *   browser_assets_ttl  EDGE_CACHE_ASSETS_TTL   default: 31536000 (1 year)
     *       Only safe because the assets are fingerprinted (app.a1b2c3.js) —
     *       a new build produces a new filename, so nothing goes stale.
     *   browser_html        EDGE_CACHE_HTML         default: false
     *       Almost always false: caching HTML serves one user's authenticated
     *       page to the next visitor.
     *   cloudflare          EDGE_CACHE_CLOUDFLARE   default: true
     *       Adds `immutable` to the asset Cache-Control, which CDNs honour.
     */
    'cache' => [
        'browser_assets'     => filter_var(env('EDGE_CACHE_ASSETS', 'true'), FILTER_VALIDATE_BOOL),
        'browser_assets_ttl' => (int) (env('EDGE_CACHE_ASSETS_TTL') ?: 31536000),
        'browser_html'       => filter_var(env('EDGE_CACHE_HTML', 'false'), FILTER_VALIDATE_BOOL),
        'cloudflare'         => filter_var(env('EDGE_CACHE_CLOUDFLARE', 'true'), FILTER_VALIDATE_BOOL),
    ],

    /**
     * 'compression'  EDGE_COMPRESSION  default: auto
     * values: auto | brotli | gzip | off
     *
     * `auto` is resolved PER SERVER at render time from that server's own
     * capability — nginx from its ngx_brotli build, Apache from its loaded
     * mod_brotli — falling back to gzip.
     *
     * An explicit `brotli` also degrades to gzip on a server without the
     * module, so a wrong choice can never break the config test. Brotli mode
     * still emits a gzip block for clients that do not send `br`.
     * An unrecognised value is treated as `auto`.
     */
    'compression' => (static function (): string {
        $mode = strtolower(trim((string) env('EDGE_COMPRESSION', 'auto')));
        return in_array($mode, ['auto', 'brotli', 'gzip', 'off'], true) ? $mode : 'auto';
    })(),

    /**
     * 'http_prelude'  EDGE_HTTP_PRELUDE  default: false  ← OPT-IN
     *
     * Prerequisites emitted ONCE at the top of the generated file: the
     * `log_format`, the rate-limit ZONES, and the Cloudflare real-IP ranges.
     *
     * Why opt-in: if your own nginx.conf already declares `log_format cf_realip`
     * or `limit_req_zone … zone=general`, declaring them again is a duplicate
     * definition and nginx refuses to start. Turn this on only when Edge owns
     * those definitions.
     *
     * IMPORTANT: rate limiting below does nothing until this is on, because the
     * zones it references are declared here.
     *
     *   log_format / log_buffer / log_flush
     *       EDGE_LOG_FORMAT (cf_realip) · EDGE_LOG_BUFFER (32k) · EDGE_LOG_FLUSH (5s)
     *       Buffered access logging: fewer disk writes on a busy host.
     *
     *   rate_limit.*  —  the per-vhost limits, applied to the APPLICATION only
     *       (the PHP front controller / the proxy location), never to static
     *       assets: at server scope one page load pulling 30 files would burn 31
     *       tokens and 429 a real visitor on CSS while the expensive dynamic
     *       request went unprotected.
     *
     *       enabled      EDGE_RATE_LIMIT        default: true
     *       req_zone     EDGE_RATE_REQ_ZONE     default: general   (zone name)
     *       req_size     EDGE_RATE_REQ_SIZE     default: 10m       (~160k IPs)
     *       req_rate     EDGE_RATE_REQ_RATE     default: 10r/s     (sustained)
     *       req_burst    EDGE_RATE_REQ_BURST    default: 50        (queue depth)
     *       req_nodelay  EDGE_RATE_REQ_NODELAY  default: true
     *           true  = serve the burst immediately, then throttle (feels fast)
     *           false = space the burst out evenly (smoother backend load)
     *       conn_zone / conn_size / conn_limit   concurrent connections per IP
     *
     *       A tripped limit answers 429 (not nginx's default 503, which this
     *       vhost maps to the error page and which reads as an outage).
     *
     *   cloudflare.*  —  restore the visitor's real IP behind Cloudflare, so
     *       logs, rate limits and deny rules see the client and not a CF edge.
     *       enabled  EDGE_CLOUDFLARE_REAL_IP  default: true
     *       header   EDGE_CLOUDFLARE_HEADER   default: CF-Connecting-IP
     *       ranges   EDGE_CLOUDFLARE_RANGES   default: CF's published list
     *                (www.cloudflare.com/ips) — override as a comma list.
     */
    'http_prelude' => [
        'enabled' => filter_var(env('EDGE_HTTP_PRELUDE', 'false'), FILTER_VALIDATE_BOOL),

        'log_format'      => (string) (env('EDGE_LOG_FORMAT') ?: 'cf_realip'),
        'log_buffer'      => (string) (env('EDGE_LOG_BUFFER') ?: '32k'),
        'log_flush'       => (string) (env('EDGE_LOG_FLUSH') ?: '5s'),

        'rate_limit' => [
            'enabled'    => filter_var(env('EDGE_RATE_LIMIT', 'true'), FILTER_VALIDATE_BOOL),
            'req_zone'   => (string) (env('EDGE_RATE_REQ_ZONE') ?: 'general'),
            'req_size'   => (string) (env('EDGE_RATE_REQ_SIZE') ?: '10m'),
            'req_rate'   => (string) (env('EDGE_RATE_REQ_RATE') ?: '10r/s'),
            'req_burst'  => (int) (env('EDGE_RATE_REQ_BURST') ?: 50),
            'req_nodelay' => filter_var(env('EDGE_RATE_REQ_NODELAY', 'true'), FILTER_VALIDATE_BOOL),
            'conn_zone'  => (string) (env('EDGE_RATE_CONN_ZONE') ?: 'perip'),
            'conn_size'  => (string) (env('EDGE_RATE_CONN_SIZE') ?: '10m'),
            'conn_limit' => (int) (env('EDGE_RATE_CONN_LIMIT') ?: 100),
        ],

        'cloudflare' => [
            'enabled' => filter_var(env('EDGE_CLOUDFLARE_REAL_IP', 'true'), FILTER_VALIDATE_BOOL),
            'header'  => (string) (env('EDGE_CLOUDFLARE_HEADER') ?: 'CF-Connecting-IP'),
            'ranges'  => array_values(array_filter(array_map('trim', explode(',', (string) env('EDGE_CLOUDFLARE_RANGES', ''))))),
        ],
    ],

    // ═══════════════════════════════════════════════════════════════════════
    //  3 · SECURITY
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * 'cors'  —  who may call this origin from a browser.
     *
     *   mode         EDGE_CORS              default: off
     *                values: off | allowlist | wildcard
     *   origins      EDGE_CORS_ORIGINS      https://a.com,https://b.com
     *   methods      EDGE_CORS_METHODS      default: GET, POST, PUT, DELETE, PATCH, OPTIONS
     *   headers      EDGE_CORS_HEADERS      default: Content-Type, Authorization, X-Requested-With
     *   credentials  EDGE_CORS_CREDENTIALS  default: false
     *
     * `allowlist` echoes the request Origin back only when it is on your list
     * (via an `$http_origin` map) — this is the mode you want.
     *
     * The wildcard is OPT-IN on purpose: `*` together with
     * `Allow-Headers: Authorization` on a host reachable beyond localhost lets
     * ANY page a developer visits make authenticated cross-origin reads of your
     * API. An allowlist with no origins degrades to `off` rather than to `*`.
     */
    'cors' => [
        'mode'        => strtolower(trim((string) env('EDGE_CORS', 'off'))),
        'origins'     => array_values(array_filter(array_map('trim', explode(',', (string) env('EDGE_CORS_ORIGINS', ''))))),
        'methods'     => (string) (env('EDGE_CORS_METHODS') ?: 'GET, POST, PUT, DELETE, PATCH, OPTIONS'),
        'headers'     => (string) (env('EDGE_CORS_HEADERS') ?: 'Content-Type, Authorization, X-Requested-With'),
        'credentials' => filter_var(env('EDGE_CORS_CREDENTIALS', 'false'), FILTER_VALIDATE_BOOL),
    ],

    /**
     * 'security'  —  hardening applied to every generated vhost.
     *
     * The rule for these defaults: anything that cannot break a normal site is
     * ON; anything that can (CSP, origin lockdown, PROXY protocol) is OFF until
     * you switch it on deliberately.
     */
    'security' => [

        /**
         * 'httpoxy_guard'  EDGE_HTTPOXY_GUARD  default: true
         *
         * Blanks HTTP_PROXY for the FastCGI request (nginx), and drops the
         * `Proxy:` request header entirely (Apache).
         *
         * The attack (CVE-2016-5385): a request carrying `Proxy: http://evil`
         * arrives in PHP as $_SERVER['HTTP_PROXY']. HTTP clients that honour
         * that variable will route YOUR server's outbound calls — payment APIs,
         * webhooks, internal services — through the attacker's proxy. The
         * distro's fastcgi_params does not clear it. The variable is only ever
         * attacker-supplied, so there is no reason to keep it.
         */
        'httpoxy_guard' => filter_var(env('EDGE_HTTPOXY_GUARD', 'true'), FILTER_VALIDATE_BOOL),

        /**
         * 'hide_upstream_headers'  EDGE_HIDE_HEADERS
         * default: X-Powered-By,X-Runtime,X-AspNet-Version,X-Drupal-Cache
         *
         * Response headers stripped before they leave the proxy. PHP's
         * `expose_php` emits `X-Powered-By: PHP/8.3.6`, handing any scanner the
         * exact patch level to look up. Costs nothing to remove.
         */
        'hide_upstream_headers' => array_values(array_filter(array_map('trim', explode(
            ',',
            (string) (env('EDGE_HIDE_HEADERS') ?: 'X-Powered-By,X-Runtime,X-AspNet-Version,X-Drupal-Cache'),
        )))),

        /**
         * Isolation headers. Set any to an EMPTY string to omit that header.
         *
         * 'permissions_policy'  EDGE_PERMISSIONS_POLICY
         *     Turns off device APIs the app never asked for, so injected script
         *     cannot reach the camera, microphone or geolocation.
         *
         * 'coop'  EDGE_COOP  default: same-origin
         *     Cross-Origin-Opener-Policy: severs the window.opener link to
         *     other origins, which is what makes Spectre-class cross-window
         *     leaks and tab-nabbing possible.
         *
         * 'corp'  EDGE_CORP  default: same-origin
         *     Cross-Origin-Resource-Policy: other sites cannot embed your
         *     resources. Relax to `cross-origin` if you intentionally serve
         *     fonts/images to other domains from this vhost.
         */
        'permissions_policy' => (string) (env('EDGE_PERMISSIONS_POLICY')
            ?? 'camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), gyroscope=()'),
        'coop' => (string) (env('EDGE_COOP') ?? 'same-origin'),
        'corp' => (string) (env('EDGE_CORP') ?? 'same-origin'),

        /**
         * 'csp' / 'csp_report_only'  EDGE_CSP / EDGE_CSP_REPORT_ONLY
         * default: '' (not emitted) / false
         *
         * Content-Security-Policy is the strongest defence against XSS: it
         * tells the browser which script sources are legitimate, so an injected
         * <script> simply does not run.
         *
         * It ships EMPTY because a policy is app-specific and a wrong one
         * breaks the site silently. Recommended rollout:
         *
         *   1. EDGE_CSP="default-src 'self'; img-src 'self' data:"
         *      EDGE_CSP_REPORT_ONLY=1        ← observe, enforce nothing
         *   2. Watch the browser console / report endpoint for violations.
         *   3. Widen the policy until it is clean, then drop REPORT_ONLY.
         */
        'csp'             => (string) (env('EDGE_CSP') ?: ''),
        'csp_report_only' => filter_var(env('EDGE_CSP_REPORT_ONLY', 'false'), FILTER_VALIDATE_BOOL),

        /**
         * 'timeouts'  EDGE_TIMEOUTS  default: true
         *
         * Slowloris / slow-POST guards. nginx ships 60-second header and body
         * timeouts, so a few dozen sockets dribbling one byte at a time can
         * occupy every worker slot without ever completing a request — a denial
         * of service that needs almost no bandwidth.
         *
         *   client_header   EDGE_CLIENT_HEADER_TIMEOUT   default: 10s
         *   client_body     EDGE_CLIENT_BODY_TIMEOUT     default: 15s
         *   send            EDGE_SEND_TIMEOUT            default: 30s
         *   keepalive       EDGE_KEEPALIVE_TIMEOUT       default: 30s
         *   header_buffers  EDGE_LARGE_CLIENT_HEADER_BUFFERS  default: 4 16k
         *
         * Raise client_body on a site that accepts large uploads over slow
         * links. Apache gets the equivalent `RequestReadTimeout` (only when
         * mod_reqtimeout is loaded).
         */
        'timeouts' => [
            'enabled'        => filter_var(env('EDGE_TIMEOUTS', 'true'), FILTER_VALIDATE_BOOL),
            'client_header'  => (string) (env('EDGE_CLIENT_HEADER_TIMEOUT') ?: '10s'),
            'client_body'    => (string) (env('EDGE_CLIENT_BODY_TIMEOUT') ?: '15s'),
            'send'           => (string) (env('EDGE_SEND_TIMEOUT') ?: '30s'),
            'keepalive'      => (string) (env('EDGE_KEEPALIVE_TIMEOUT') ?: '30s'),
            'header_buffers' => (string) (env('EDGE_LARGE_CLIENT_HEADER_BUFFERS') ?: '4 16k'),
        ],

        /**
         * 'max_body'  EDGE_MAX_BODY  default: 25m     (25m | 1g | 512k …)
         *
         * The request-body ceiling — a security knob, not a preference: it
         * bounds how much a single request can make the box buffer.
         *
         *   pure JSON API      1m     upload/media site   200m or more
         *
         * A too-small value shows up as HTTP 413 on upload. Converted to bytes
         * automatically for Apache's LimitRequestBody. An unparseable value
         * falls back to 25m rather than emitting something invalid.
         */
        'max_body' => (string) (env('EDGE_MAX_BODY') ?: '25m'),

        /**
         * 'uploads'  —  make user-uploaded files harmless.
         *
         *   mode       EDGE_UPLOAD_MODE   default: attachment
         *              values: attachment | deny-risky | off
         *   paths      EDGE_UPLOAD_PATHS  default: storage,uploads,media
         *   risky_ext  EDGE_UPLOAD_RISKY_EXT
         *
         * Uploads are served from your OWN origin, and `storage` is deliberately
         * not in the deny list (the public/storage symlink serves intended
         * files). So an uploaded .svg — which can contain <script> — or an .html
         * file is stored XSS against every session on the domain.
         *
         *   attachment  force a download instead of rendering, plus a sandbox
         *               CSP. The file stays reachable; it just cannot execute.
         *   deny-risky  refuse those extensions outright (strictest).
         *   off         emit nothing (only if uploads are on another domain).
         *
         * Strongest option overall: serve uploads from a separate cookieless
         * domain, and set this to `off` here.
         */
        'uploads' => [
            'mode'  => strtolower(trim((string) (env('EDGE_UPLOAD_MODE') ?: 'attachment'))),
            'paths' => array_values(array_filter(array_map('trim', explode(
                ',',
                (string) (env('EDGE_UPLOAD_PATHS') ?: 'storage,uploads,media'),
            )))),
            'risky_ext' => (string) (env('EDGE_UPLOAD_RISKY_EXT')
                ?: 'svg|svgz|html|htm|xhtml|xml|shtml|phtml|php|php\\d|phar|js|mjs|wasm'),
        ],

        /**
         * 'proxy_protocol'  EDGE_PROXY_PROTOCOL  default: false
         *
         * Carries the REAL client address from the SNI stream splitter to the
         * backend vhosts.
         *
         * The problem it solves: a plain layer-4 `proxy_pass` rewrites the
         * source address, so behind the splitter every visitor arrives at the
         * backend as 127.0.0.1. Per-IP rate limiting collapses into one shared
         * bucket (one noisy client 429s everyone), and with the Cloudflare
         * real-IP prelude on, 127.0.0.1 is a TRUSTED proxy — so any client can
         * send its own CF-Connecting-IP header and choose its rate-limit
         * identity, defeating throttling entirely.
         *
         * OFF by default because it must match on BOTH ends: a backend that
         * expects the header and a router that does not send it (or the
         * reverse) breaks every request. Edge emits both ends from this one
         * flag, and never puts it on a directly-reachable vhost.
         *
         * Turn it on when Edge owns the splitter (EDGE_REUSE_STREAM=0), or when
         * your own SNI router is configured to send it.
         *
         * Note: behind Cloudflare the recovered address is the CF edge, not the
         * visitor (nginx cannot chain two real-IP passes) — but it is an
         * address the client cannot forge.
         */
        'proxy_protocol' => filter_var(env('EDGE_PROXY_PROTOCOL', 'false'), FILTER_VALIDATE_BOOL),

        /**
         * Origin lockdown — stop traffic that skips your CDN/WAF entirely.
         *
         *   cloudflare_only  EDGE_CLOUDFLARE_ONLY  default: false
         *       Allow Cloudflare's published ranges (plus loopback) and deny
         *       everything else.
         *   origin_pull_ca   EDGE_ORIGIN_PULL_CA   default: '' (off)
         *       Path to Cloudflare's origin-pull CA. Enables Authenticated
         *       Origin Pulls (mTLS): only a client presenting a certificate
         *       from that CA may connect. Requires a TLS mode.
         *
         * Why: restoring the real IP from CF headers does NOT stop anyone who
         * learns your origin address from hitting it directly and bypassing
         * every edge rule you configured. mTLS is the stronger of the two,
         * because an IP allowlist has to be maintained as ranges change.
         */
        'cloudflare_only' => filter_var(env('EDGE_CLOUDFLARE_ONLY', 'false'), FILTER_VALIDATE_BOOL),
        'origin_pull_ca'  => (string) (env('EDGE_ORIGIN_PULL_CA') ?: ''),
    ],

    /**
     * 'deny_dirs'  EDGE_DENY_DIRS
     * default: vendor,node_modules,tests,.git,.github,bootstrap/cache
     *
     * Directories denied by prefix, evaluated BEFORE the static-asset rule so
     * nothing inside them can be served just because it ends in .js or .css.
     *
     * `storage` is deliberately NOT in the default: a Laravel-style
     * public/storage symlink serves intended user files, and a blanket deny
     * would break it. Add it where your app has no such symlink.
     *
     * Empty disables directory denies. Entries containing `..` are dropped.
     */
    'deny_dirs' => (static function (): array {
        $raw = env('EDGE_DENY_DIRS');
        if ($raw === null || $raw === '') {
            return ['vendor', 'node_modules', 'tests', '.git', '.github', 'bootstrap/cache'];
        }
        return array_values(array_filter(array_map('trim', explode(',', (string) $raw))));
    })(),

    /**
     * 'deny_ext'  EDGE_DENY_EXT   (pipe-separated: env|log|pem|…)
     *
     * File extensions never served as static content.
     *
     * This matters more than it looks: `location /` ends in `try_files $uri …`,
     * which happily serves ANY file that exists in the public root. This list
     * is the only thing between a stray `backup.sql`, `server.key` or
     * `site.zip` and the internet — and a leaked archive is a classic way an
     * origin gets fully compromised.
     *
     * Covers: dumps and databases, editor/backup leftovers, shell scripts and
     * config, private keys and keystores, and archives.
     *
     * Deliberately NOT here: a blanket `json`. Vite's manifest.json, web app
     * manifests and .well-known/*.json are legitimate — risky JSON is denied by
     * NAME in deny_files instead. Source maps (.map) are added automatically in
     * the PRODUCTION profile only (they expose your original source), and kept
     * in development for debugging.
     */
    'deny_ext' => (string) (env('EDGE_DENY_EXT') ?: implode('|', [
        'env', 'log', 'sql', 'sqlite', 'sqlite3', 'db', 'db3',
        'bak', 'backup', 'old', 'orig', 'rej', 'save', 'swp', 'swo', 'tmp',
        'dist', 'sh', 'bash', 'zsh', 'ini', 'conf', 'cnf', 'yml', 'yaml', 'lock',
        'pem', 'key', 'crt', 'cer', 'csr', 'der', 'p12', 'pfx', 'jks', 'asc', 'gpg', 'kdbx',
        'zip', 'tar', 'gz', 'tgz', 'bz2', 'xz', '7z', 'rar', 'iso', 'dmg',
    ])),

    /**
     * 'deny_files'  EDGE_DENY_FILES   (comma-separated exact filenames)
     *
     * Denied by name, whatever the extension — build and deploy metadata that
     * no extension rule would catch. `composer.lock` and `package-lock.json`
     * publish your exact dependency versions, which turns a CVE feed into a
     * shopping list for your host.
     */
    'deny_files' => array_values(array_filter(array_map('trim', explode(',', (string) (env('EDGE_DENY_FILES') ?: implode(',', [
        'composer.json', 'composer.lock', 'package.json', 'package-lock.json',
        'yarn.lock', 'pnpm-lock.yaml', 'Dockerfile', 'docker-compose.yml',
        'Makefile', 'Procfile', '.htpasswd', 'phpunit.xml', 'proj.json', 'module.json',
    ])))))),

    /**
     * 'allowed_methods'  EDGE_ALLOWED_METHODS
     * default: GET|HEAD|POST|PUT|PATCH|DELETE|OPTIONS
     *
     * Everything outside this set is refused with 405 before it reaches PHP.
     *
     * The default is the full REST set because these apps genuinely use
     * PUT/PATCH/DELETE; it still blocks the oddities (TRACE, CONNECT, WebDAV
     * verbs like PROPFIND). Tighten to `GET|HEAD|POST` for a classic form app.
     * Empty disables the guard.
     */
    'allowed_methods' => (string) (env('EDGE_ALLOWED_METHODS') ?: 'GET|HEAD|POST|PUT|PATCH|DELETE|OPTIONS'),

    /**
     * 'debug_log'  EDGE_NGINX_DEBUG_LOG  default: false
     *
     * Sets the vhost error_log level to `debug` instead of `warn`. OPT-IN
     * because it needs an nginx built --with-debug, produces gigabytes, and can
     * write request internals containing session ids and tokens to disk.
     */
    'debug_log' => filter_var(env('EDGE_NGINX_DEBUG_LOG', 'false'), FILTER_VALIDATE_BOOL),

    /**
     * 'nginx_status'  EDGE_NGINX_STATUS  default: true
     *
     * Emits the /nginx-status stub_status endpoint — but ONLY on a true
     * DEVELOPMENT profile, never in production, and never merely because
     * EDGE_DEV_VHOST was forced on.
     *
     * The reason: behind the :443 SNI stream splitter every peer looks like
     * 127.0.0.1, so an `allow 127.0.0.1` rule there would publish your server
     * statistics to the entire internet.
     */
    'nginx_status' => filter_var(env('EDGE_NGINX_STATUS', 'true'), FILTER_VALIDATE_BOOL),

    /**
     * 'per_site_logs'  EDGE_PER_SITE_LOGS  default: true
     *
     * One access/error log pair per project (<name>.access.log). Emitted in
     * both profiles: they matter MOST in production, where an incident has to
     * be reconstructed across many domains sharing one host. False falls back
     * to nginx's single global log.
     */
    'per_site_logs' => filter_var(env('EDGE_PER_SITE_LOGS', 'true'), FILTER_VALIDATE_BOOL),

    /**
     * 'dev_vhost'  EDGE_DEV_VHOST  default: null (follow APP_ENV)
     *
     * Dev-only vhost extras: verbose logging and a Disallow-all robots.txt.
     * NULL means "follow the APP_ENV cache profile"; set 1/0 to force.
     *
     * Deliberately NOT derived from HKM_DEV — which kernel you run and which
     * environment the app is in are independent decisions.
     */
    'dev_vhost' => ((string) env('EDGE_DEV_VHOST', '')) === ''
        ? null
        : filter_var(env('EDGE_DEV_VHOST'), FILTER_VALIDATE_BOOL),

    // ═══════════════════════════════════════════════════════════════════════
    //  4 · STRATEGY, UPSTREAMS & OUTPUT
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * 'upstreams'  —  where traffic is actually sent.
     *
     *   nginx   EDGE_NGINX_BACKEND   default: 127.0.0.1:444
     *       Where nginx terminates TLS for the platform's own domains (the
     *       backend of the SNI splitter). Its port also becomes the internal
     *       listen port when a splitter owns :443.
     *   apache  EDGE_APACHE_BACKEND  default: 127.0.0.1:8443
     *       The fallback server for every host the platform does not own — the
     *       `default` branch of the SNI map. This is what lets Edge take over
     *       :443 without disturbing the other sites on the box.
     *   app     EDGE_APP_BACKEND     default: 127.0.0.1:8080
     *       A plain application upstream for reverse-proxy templates.
     */
    'upstreams' => [
        'nginx'  => (string) (env('EDGE_NGINX_BACKEND') ?: '127.0.0.1:444'),
        'apache' => (string) (env('EDGE_APACHE_BACKEND') ?: '127.0.0.1:8443'),
        'app'    => (string) (env('EDGE_APP_BACKEND') ?: '127.0.0.1:8080'),
    ],

    /**
     * 'paths'  —  where each rendered file is written.
     *
     *   stream  EDGE_STREAM_PATH  default: var/edge/hkm-edge-stream.conf
     *   nginx   EDGE_NGINX_PATH   default: var/edge/hkm-edge-nginx.conf
     *   apache  EDGE_APACHE_PATH  default: var/edge/hkm-edge-apache.conf
     *
     * Defaults land under var/edge/ so you can generate and inspect the config
     * with no root at all. In production point them at the real include dirs:
     *
     *   EDGE_NGINX_PATH=/etc/nginx/sites-enabled/hkm.conf
     *   EDGE_STREAM_PATH=/etc/nginx/hkm-stream.conf   ← must be included at the
     *       nginx MAIN context (top level of nginx.conf), NOT inside http {}.
     *
     * Writes are atomic (temp file + rename) and the previous file is backed up
     * and restored automatically if the config test fails.
     */
    'paths' => [
        'stream' => (string) (env('EDGE_STREAM_PATH') ?: base_path('var/edge/hkm-edge-stream.conf')),
        'nginx'  => (string) (env('EDGE_NGINX_PATH')  ?: base_path('var/edge/hkm-edge-nginx.conf')),
        'apache' => (string) (env('EDGE_APACHE_PATH') ?: base_path('var/edge/hkm-edge-apache.conf')),
    ],

    /**
     * 'commands'  —  how the config is validated and reloaded.
     *
     *   nginx_test / nginx_reload    EDGE_NGINX_TEST_CMD / EDGE_NGINX_RELOAD_CMD
     *   apache_test / apache_reload  EDGE_APACHE_TEST_CMD / EDGE_APACHE_RELOAD_CMD
     *
     * Override per distro or init system, e.g.
     *   EDGE_NGINX_RELOAD_CMD="systemctl reload nginx"
     *   EDGE_APACHE_RELOAD_CMD="sudo apachectl graceful"
     *
     * The test command runs BEFORE the reload; if it fails, the previous config
     * is restored automatically, so a broken generate never becomes an outage.
     *
     * Safety: the effective binary is checked against an allow-list (nginx,
     * apachectl, systemctl, service, …) before anything executes, and shell
     * metacharacters are rejected — configuration is a weaker trust boundary
     * than code, and these commands typically run as root. Add a distro-specific
     * binary with EDGE_ALLOWED_BINARIES rather than editing the plugin.
     */
    'commands' => [
        'nginx_test'    => (string) (env('EDGE_NGINX_TEST_CMD')    ?: 'nginx -t'),
        'nginx_reload'  => (string) (env('EDGE_NGINX_RELOAD_CMD')  ?: 'nginx -s reload'),
        'apache_test'   => (string) (env('EDGE_APACHE_TEST_CMD')   ?: 'apachectl configtest'),
        'apache_reload' => (string) (env('EDGE_APACHE_RELOAD_CMD') ?: 'apachectl graceful'),
    ],

    /**
     * 'force_strategy'  EDGE_FORCE_STRATEGY  default: '' (auto-detect)
     * values: '' | nginx-only | apache-only
     *
     * By default Edge probes the host and picks:
     *   nginx + Apache running, nginx has stream → SNI splitter
     *   nginx only                               → nginx reverse proxy
     *   Apache only                              → Apache VirtualHost
     *   neither                                  → nothing
     *
     * Set this to pin ONE server with NO fallback, regardless of what else is
     * running. Per run: `edge:apply --nginx-only` / `--apache-only`. A pinned
     * run also skips probing the other server entirely, so the reported stack
     * matches the plan.
     */
    'force_strategy' => (static function (): string {
        $v = strtolower(trim((string) env('EDGE_FORCE_STRATEGY', '')));
        return in_array($v, ['nginx-only', 'nginx', 'apache-only', 'apache'], true) ? $v : '';
    })(),

    /**
     * 'reuse_stream'  EDGE_REUSE_STREAM  default: true
     *
     * When both servers run and nginx ALREADY has an SNI splitter (a `stream {}`
     * block using ssl_preread), reuse it instead of writing a second,
     * conflicting one.
     *
     * Edge then emits only the internal backend vhosts and MERGES the platform's
     * domains into your existing `map $ssl_preread_server_name`, in place. Your
     * hand-written entries are untouched; the additions live in a marked,
     * idempotent sub-block before the `default` line, so re-runs never
     * duplicate. Editing nginx.conf usually needs sudo, and a failed write
     * fails the whole apply loudly rather than reporting success.
     *
     * Set false to always write Edge's own stream block instead.
     */
    'reuse_stream' => filter_var(env('EDGE_REUSE_STREAM', 'true'), FILTER_VALIDATE_BOOL),

    /**
     * 'nginx_ssl_port'    EDGE_NGINX_SSL_PORT     default: 0 (auto)
     * 'behind_sni_router' EDGE_BEHIND_SNI_ROUTER  default: false
     *
     * Which port the nginx-only vhost LISTENS on.
     *
     * Standalone that is the public port (443). But when this host also runs an
     * SNI `stream {}` router, that router already binds :443 — emitting
     * `listen 443 ssl` as well makes nginx fail to start with "Address already
     * in use", taking the whole server down.
     *
     * Auto-detected when an existing splitter is found. Force the topology with
     * EDGE_BEHIND_SNI_ROUTER=1, or pin the exact port with EDGE_NGINX_SSL_PORT.
     * The :80 → HTTPS redirect still targets the PUBLIC port either way.
     */
    'nginx_ssl_port'    => (int) (env('EDGE_NGINX_SSL_PORT') ?: 0),
    'behind_sni_router' => filter_var(env('EDGE_BEHIND_SNI_ROUTER', 'false'), FILTER_VALIDATE_BOOL),

    /**
     * 'stream_backend'  EDGE_STREAM_BACKEND  default: nginx_backend
     *
     * The upstream NAME that merged domains point at inside your existing
     * splitter's map. It must match an `upstream { … }` already declared in
     * your nginx.conf (the default one resolves to 127.0.0.1:444).
     * Only used when reusing an existing stream splitter.
     */
    'stream_backend' => (string) (env('EDGE_STREAM_BACKEND') ?: 'nginx_backend'),

    /**
     * 'reload'  EDGE_RELOAD  default: false
     *
     * Whether `edge:apply` validates and reloads after writing. Off by default
     * so a bare apply never touches a running server until you opt in. Per run:
     * `--no-reload` to skip. The reload always runs the test command first.
     */
    'reload' => filter_var(env('EDGE_RELOAD', 'false'), FILTER_VALIDATE_BOOL),

    // ═══════════════════════════════════════════════════════════════════════
    //  5 · DOMAINS & /etc/hosts
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * 'projects_registry' / 'platform_registry'
     *
     * Read automatically from the resolved projects dir (see the top of this
     * file). projects.json maps project → path + domains; platform.json holds
     * the subdomain registry. You rarely set these directly — point
     * EDGE_PROJECTS_DIR at a different registry instead.
     */
    'projects_registry' => $__edgeProjectsDir . '/projects.json',
    'platform_registry' => $__edgeProjectsDir . '/platform.json',

    /**
     * 'extra_domains' / 'exclude_domains'
     * EDGE_EXTRA_DOMAINS / EDGE_EXCLUDE_DOMAINS   (comma-separated)
     *
     * Add or drop hostnames without editing proj.json — handy for a temporary
     * vanity domain, or for excluding one host while you migrate it. Every
     * hostname is validated against a strict charset before it can reach a
     * rendered config, so a malformed entry can never inject directives.
     */
    'extra_domains'   => array_values(array_filter(array_map('trim', explode(',', (string) env('EDGE_EXTRA_DOMAINS', ''))))),
    'exclude_domains' => array_values(array_filter(array_map('trim', explode(',', (string) env('EDGE_EXCLUDE_DOMAINS', ''))))),

    /**
     * 'local_tlds'  EDGE_LOCAL_TLDS
     * default: local,test,localhost,example,invalid
     *
     * Which hostnames count as DEV-ONLY. A domain whose TLD is in this list —
     * or that has no dot at all (`myapp`) — is treated as local: it goes to
     * /etc/hosts pointing at the loopback rather than into the public config.
     *
     * Exception: if a project's domains are ALL local, they are served anyway.
     * There is nothing else that project could serve, and rendering an empty
     * config instead would just look like the tool was broken.
     */
    'local_tlds' => array_values(array_filter(array_map('trim', explode(',', (string) env('EDGE_LOCAL_TLDS', 'local,test,localhost,example,invalid'))))),

    /**
     * 'manage_hosts'  EDGE_MANAGE_HOSTS  default: true
     * 'hosts.path'    EDGE_HOSTS_PATH    default: /etc/hosts
     * 'hosts.ip'      EDGE_HOSTS_IP      default: 127.0.0.1
     *
     * Whether `edge:apply` also syncs local domains into the hosts file.
     *
     * This only ever runs in dev mode (`hkm … --dev`, which exports HKM_DEV=1):
     * a live server resolves its domains through DNS, so a production apply
     * silently skips the step and never touches the machine's hosts file.
     *
     * Only a marked block is managed — the rest of your hosts file is preserved
     * byte for byte, a hostname you mapped by hand elsewhere is left
     * authoritative, and re-runs never duplicate. `edge:hosts --remove` deletes
     * the managed block and nothing else. Editing /etc/hosts needs sudo.
     */
    'manage_hosts' => filter_var(env('EDGE_MANAGE_HOSTS', 'true'), FILTER_VALIDATE_BOOL),
    'hosts' => [
        'path' => (string) (env('EDGE_HOSTS_PATH') ?: '/etc/hosts'),
        'ip'   => (string) (env('EDGE_HOSTS_IP') ?: '127.0.0.1'),
    ],

    /**
     * 'include_local_in_server'  EDGE_LOCAL_IN_SERVER  default: false
     *
     * Also serve local (.local/.test) domains from the generated vhost, for a
     * project that has public domains too.
     *
     * Dev mode turns this on automatically, so `hkm cli -p <p> --dev edge:apply`
     * gives you a working local site with no extra flag. Set it true to get the
     * same behaviour outside dev. Local domains are written to /etc/hosts
     * either way.
     */
    'include_local_in_server' => filter_var(env('EDGE_LOCAL_IN_SERVER', 'false'), FILTER_VALIDATE_BOOL),

    // ═══════════════════════════════════════════════════════════════════════
    //  6 · SERVING & RUN ENVIRONMENT
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * 'serve'  —  how each project's PHP actually runs.
     *
     * Per-project override in proj.json (this is the usual place to set it):
     *
     *   { "edge": { "runtime": "openswoole",
     *               "openswoole": { "host": "127.0.0.1", "port": 9501,
     *                               "ports": [9501, 9502],
     *                               "websocket": "/ws", "health": "/health",
     *                               "php": "/usr/bin/php8.3",
     *                               "command": "app/swoole/index.php",
     *                               "workers": "auto" } } }
     *
     * `runtime` accepts php-fpm | openswoole (and the legacy fpm | swoole).
     * A project with nothing set stays on PHP-FPM, so existing configs are
     * unchanged.
     *
     *   model       EDGE_SERVE_MODEL  default: php-fpm
     *       php-fpm     nginx/Apache serve the docroot and pass PHP to FPM.
     *       openswoole  the project runs its own HTTP server; nginx reverse-
     *                   proxies to it and still serves static files off disk.
     *
     *   fpm_socket  EDGE_FPM_SOCKET  default: '' (auto)
     *       Empty auto-resolves the socket matching the CLI PHP version, which
     *       is what makes a multi-PHP host bind each site to the right pool:
     *         versioned socket for this PHP → any versioned (newest) → generic
     *         → 127.0.0.1:9000.
     *       Pin it explicitly to override, e.g. unix:/run/php/php8.4-fpm.sock.
     *
     * OpenSwoole settings:
     *   swoole_host / swoole_port   EDGE_SWOOLE_HOST / EDGE_SWOOLE_PORT
     *       Where the app's server listens — nginx proxies here.
     *   websocket_path              EDGE_SWOOLE_WS_PATH   default: /ws
     *       A dedicated WebSocket location. Empty disables the extra block (the
     *       `/` proxy still carries the Upgrade headers).
     *   swoole_php / swoole_command / swoole_workers
     *       Used by the unit `edge:service` generates. `command` is relative to
     *       PROJECT_ROOT (absolute paths are used as-is) and matches what
     *       `hkm run <project> --swoole` executes.
     *   swoole_balance              default: least_conn ('' = round-robin)
     *       With several ports/servers configured this is the load-balancing
     *       method for the upstream pool.
     *   swoole_max_fails / swoole_fail_timeout
     *       When to consider a backend down and stop sending it traffic.
     *   swoole_keepalive*           idle upstream connections kept per worker
     *       Reuses TCP connections to the app — meaningful latency saving on a
     *       busy site. 0 disables the pool; the *_timeout/_requests values are
     *       omitted from the config when empty/0.
     *   health.enabled / health.path  EDGE_HEALTH_CHECK / EDGE_HEALTH_PATH
     *       An extra location proxied to the app for load-balancer probes.
     */
    'serve' => [
        'model'            => (string) (env('EDGE_SERVE_MODEL') ?: 'php-fpm'), // php-fpm | openswoole
        'fpm_socket'       => (string) env('EDGE_FPM_SOCKET', ''),

        'swoole_host'      => (string) (env('EDGE_SWOOLE_HOST') ?: '127.0.0.1'),
        'swoole_port'      => (int) (env('EDGE_SWOOLE_PORT') ?: env('EDGE_SWOOLE_BASE_PORT') ?: 9501),
        'websocket_path'   => (string) (env('EDGE_SWOOLE_WS_PATH') ?: '/ws'),
        'swoole_php'       => (string) (env('EDGE_SWOOLE_PHP') ?: PHP_BINARY ?: '/usr/bin/php'),
        'swoole_command'   => (string) (env('EDGE_SWOOLE_COMMAND') ?: 'app/swoole/index.php'),
        'swoole_workers'   => (string) (env('EDGE_SWOOLE_WORKERS') ?: 'auto'),
        'swoole_balance'            => (string) (env('EDGE_SWOOLE_BALANCE') ?: 'least_conn'), // '' = round-robin
        'swoole_max_fails'          => (int) (env('EDGE_SWOOLE_MAX_FAILS') ?: 3),
        'swoole_fail_timeout'       => (string) (env('EDGE_SWOOLE_FAIL_TIMEOUT') ?: '10s'),
        'swoole_keepalive'          => (int) (env('EDGE_SWOOLE_KEEPALIVE') ?: 64),   // 0 disables the pool
        'swoole_keepalive_timeout'  => (string) env('EDGE_SWOOLE_KEEPALIVE_TIMEOUT', ''),   // '' = omit
        'swoole_keepalive_requests' => (int) env('EDGE_SWOOLE_KEEPALIVE_REQUESTS', 0),      // 0 = omit

        'health'           => [
            'enabled' => filter_var(env('EDGE_HEALTH_CHECK', 'false'), FILTER_VALIDATE_BOOL),
            'path'    => (string) (env('EDGE_HEALTH_PATH') ?: '/health'),
        ],
    ],

    /**
     * 'inject_kernel_env'  EDGE_INJECT_KERNEL_ENV  default: true
     *
     * Write the kernel-resolution environment into each vhost as fastcgi_param
     * (nginx) / SetEnv (Apache).
     *
     * This is not optional plumbing: PHP-FPM workers do NOT inherit your shell
     * or the `hkm` launcher's environment, so without it the served project
     * cannot find the kernel it is supposed to boot against. Symptom when it is
     * off: the site works from the CLI and 500s in the browser.
     */
    'inject_kernel_env' => filter_var(env('EDGE_INJECT_KERNEL_ENV', 'true'), FILTER_VALIDATE_BOOL),

    /**
     * 'app_env'  EDGE_APP_ENV  default: APP_ENV, else production
     *
     * The APP_ENV written into each vhost, and what the cache profile derives
     * from. Per run: `edge:apply --local | --development | --production`.
     * Anything unrecognised falls back to the DEVELOPMENT profile — a stale
     * asset in dev is cheap, a year of wrong immutable caching is not.
     */
    'app_env' => (string) (env('EDGE_APP_ENV') ?: env('APP_ENV') ?: 'production'),

    /**
     * 'kernel_env_keys'  —  which variables get passed through to the vhost.
     *
     * The launcher (`hkm run` / `hkm cli`) already exports the right values for
     * the active context — dev (HKM_DEV_HOME + your checkout) versus live (the
     * installed kernel). Edge simply PASSES THROUGH whichever of these are
     * present; it never derives, defaults or invents them, and only the ones
     * actually set are written.
     *
     * So a dev run naturally carries HKM_DEV_HOME, a live run carries the
     * installed paths, and PSP_PROJECTS_DIR appears only if you set it.
     * Add a key here if your deployment needs another variable in the vhost.
     */
    'kernel_env_keys' => [
        'HKM_KERNEL_HOME',
        'HKM_DEV_HOME',
        'HKM_USERDATA_DIR',
        'PSP_GLOBAL_AUTOLOAD',
        'PSP_PROJECTS_DIR',
    ],
];
